// js/releases.js
// Reads public JSON generated by GitHub Actions from a private repo

const MAX_RELEASES = 5;
const STATUS_ID = "release-status";

const container = document.getElementById(STATUS_ID);

function escapeHtml(str) {
  return String(str || "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  }[c]));
}

function formatDate(iso) {
  if (!iso) return "Unpublished";
  try {
    const d = new Date(iso);
    return d.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

async function loadReleases() {
  if (!container) return;

  try {
    const res = await fetch("./data/releases.json", {
      cache: "no-store",
    });

    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`);
    }

    const releases = await res.json();

    if (!Array.isArray(releases) || releases.length === 0) {
      container.innerHTML = "<p>No releases published yet.</p>";
      return;
    }

    const cards = releases
      .slice(0, MAX_RELEASES)
      .map((r) => {
        const title = escapeHtml(r.name || r.tag_name || "Release");
        const tag = r.tag_name
          ? `<code>${escapeHtml(r.tag_name)}</code>`
          : "";
        const date = formatDate(r.published_at);
        const url = r.html_url;

        const body = (r.body || "").trim();
        const snippet = escapeHtml(body);

        return `
          <div class="release-card">
            <div class="release-title">
              <a href="${url}" target="_blank" rel="noreferrer">${title}</a>
              ${tag}
            </div>
            <div class="release-meta">Published: ${escapeHtml(date)}</div>
            ${snippet ? `<div class="release-body">${snippet}</div>` : ""}
          </div>
        `;
      })
      .join("");

    container.innerHTML = `
      <div class="release-list">
        ${cards}
      </div>
      <p class="release-footer">
        Status synced from private Capstone repository
      </p>
    `;
  } catch (err) {
    console.error("Release loader error:", err);
    container.innerHTML = `
      <p>Current status unavailable.</p>
      <p class="muted">Waiting for release data.</p>
    `;
  }
}

loadReleases();
